const hre = require("hardhat");
const fs = require("fs");
const path = require("path");

async function main() {
  console.log("🚀 Starting deployment to Sepolia...");

  const [deployer] = await hre.ethers.getSigners();
  console.log("Deploying with account:", deployer.address);

  // 1. Compile & Deploy
  const ElectronicVoting = await hre.ethers.getContractFactory("ElectronicVoting");
  const voting = await ElectronicVoting.deploy();
  
  await voting.deployed();
  const contractAddress = voting.address;

  console.log("✅ ElectronicVoting deployed to:", contractAddress);

  // 2. Lưu Config cho Frontend
  saveFrontendFiles(contractAddress);
}

function saveFrontendFiles(contractAddress) {
  const constantsDir = path.join(__dirname, "../src/constants");

  if (!fs.existsSync(constantsDir)) {
    fs.mkdirSync(constantsDir, { recursive: true });
  }

  // Đọc ABI mới nhất
  const artifactPath = path.join(__dirname, "../src/artifacts/src/contracts/ElectronicVoting.sol/ElectronicVoting.json");
  
  // Kiểm tra file tồn tại (do Hardhat đôi khi chưa ghi kịp)
  if (!fs.existsSync(artifactPath)) {
      console.error("❌ Cannot find artifact. Make sure compilation finished.");
      return;
  }
  
  const artifact = JSON.parse(fs.readFileSync(artifactPath));

  const tsContent = `// Auto-generated by scripts/deploy.js
export const VOTE_CONTRACT_ADDRESS = "${contractAddress}";
export const VOTE_CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;

  fs.writeFileSync(path.join(constantsDir, "voteContract.ts"), tsContent);
  console.log(`📝 Updated src/constants/voteContract.ts`);
}

main()
  .then(() => process.exit(0))
  .catch((error) => {
    console.error(error);
    process.exit(1);
  });